=== lvlvllvlvllvlvl/RePoE/RePoE/schema/item_classes.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/ItemClassesSchema",
    "definitions": {
        "ItemClassesSchema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "AbyssJewel": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Active Skill Gem": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Amulet": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "AnimalCharm": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "ArchnemesisMod": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "AtlasUpgradeItem": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Belt": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Body Armour": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Boots": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Bow": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Breachstone": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Claw": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Currency": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "DONOTUSE1": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "DONOTUSE2": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "DONOTUSE3": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "DONOTUSE4": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "DONOTUSE5": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "DONOTUSE6": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "DONOTUSE7": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "Dagger": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "DelveSocketableCurrency": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "DelveStackableSocketableCurrency": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "DivinationCard": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "ExpeditionLogbook": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "FishingRod": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "GiftBox": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "Gloves": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "HeistBlueprint": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "HeistContract": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "HeistEquipmentReward": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "HeistEquipmentTool": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "HeistEquipmentUtility": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "HeistEquipmentWeapon": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "HeistObjective": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Helmet": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "HiddenItem": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "HideoutDoodad": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "HybridFlask": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Incubator": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "IncubatorStackable": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "IncursionItem": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "InstanceLocalItem": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "ItemisedCorpse": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "ItemisedSanctum": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Jewel": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "LabyrinthItem": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "LabyrinthMapItem": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "LabyrinthTrinket": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "LargeRelic": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "Leaguestone": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "LifeFlask": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "ManaFlask": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Map": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "MapFragment": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "MediumRelic": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "MemoryLine": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "MetamorphosisDNA": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Microtransaction": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "MiscMapItem": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "NecropolisPack": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "One Hand Axe": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "One Hand Mace": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "One Hand Sword": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "PantheonSoul": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "QuestItem": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Quiver": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Relic": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Ring": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Rune Dagger": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "SanctumSpecialRelic": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Sceptre": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "SentinelDrone": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Shield": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "SmallRelic": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "StackableCurrency": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Staff": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Support Skill Gem": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Thrusting One Hand Sword": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Tincture": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Trinket": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Two Hand Axe": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Two Hand Mace": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Two Hand Sword": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Unarmed": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "UniqueFragment": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "UniqueShard": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "UniqueShardBase": {
                    "$ref": "#/definitions/ArchnemesisMod"
                },
                "UtilityFlask": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "UtilityFlaskCritical": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "VaultKey": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Wand": {
                    "$ref": "#/definitions/AbyssJewel"
                },
                "Warstaff": {
                    "$ref": "#/definitions/AbyssJewel"
                }
            },
            "required": [
                "AbyssJewel",
                "Active Skill Gem",
                "Amulet",
                "AnimalCharm",
                "ArchnemesisMod",
                "AtlasUpgradeItem",
                "Belt",
                "Body Armour",
                "Boots",
                "Bow",
                "Breachstone",
                "Claw",
                "Currency",
                "DONOTUSE1",
                "DONOTUSE2",
                "DONOTUSE3",
                "DONOTUSE4",
                "DONOTUSE5",
                "DONOTUSE6",
                "DONOTUSE7",
                "Dagger",
                "DelveSocketableCurrency",
                "DelveStackableSocketableCurrency",
                "DivinationCard",
                "ExpeditionLogbook",
                "FishingRod",
                "GiftBox",
                "Gloves",
                "HeistBlueprint",
                "HeistContract",
                "HeistEquipmentReward",
                "HeistEquipmentTool",
                "HeistEquipmentUtility",
                "HeistEquipmentWeapon",
                "HeistObjective",
                "Helmet",
                "HiddenItem",
                "HideoutDoodad",
                "HybridFlask",
                "Incubator",
                "IncubatorStackable",
                "IncursionItem",
                "InstanceLocalItem",
                "ItemisedCorpse",
                "ItemisedSanctum",
                "Jewel",
                "LabyrinthItem",
                "LabyrinthMapItem",
                "LabyrinthTrinket",
                "LargeRelic",
                "Leaguestone",
                "LifeFlask",
                "ManaFlask",
                "Map",
                "MapFragment",
                "MediumRelic",
                "MemoryLine",
                "MetamorphosisDNA",
                "Microtransaction",
                "MiscMapItem",
                "NecropolisPack",
                "One Hand Axe",
                "One Hand Mace",
                "One Hand Sword",
                "PantheonSoul",
                "QuestItem",
                "Quiver",
                "Relic",
                "Ring",
                "Rune Dagger",
                "SanctumSpecialRelic",
                "Sceptre",
                "SentinelDrone",
                "Shield",
                "SmallRelic",
                "StackableCurrency",
                "Staff",
                "Support Skill Gem",
                "Thrusting One Hand Sword",
                "Tincture",
                "Trinket",
                "Two Hand Axe",
                "Two Hand Mace",
                "Two Hand Sword",
                "Unarmed",
                "UniqueFragment",
                "UniqueShard",
                "UniqueShardBase",
                "UtilityFlask",
                "UtilityFlaskCritical",
                "VaultKey",
                "Wand",
                "Warstaff"
            ],
            "title": "ItemClassesSchema"
        },
        "AbyssJewel": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "category": {
                    "type": "string"
                },
                "category_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "influence_tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "category",
                "category_id",
                "name"
            ],
            "title": "AbyssJewel"
        },
        "ArchnemesisMod": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ],
            "title": "ArchnemesisMod"
        }
    }
}

=== lvlvllvlvllvlvl/RePoE/RePoE/data/Japanese/item_classes.min.json
{"LifeFlask":{"category":"フラスコ","category_id":"Flask","name":"ライフフラスコ"},"ManaFlask":{"category":"フラスコ","category_id":"Flask","name":"マナフラスコ"},"HybridFlask":{"category":"フラスコ","category_id":"Flask","name":"ハイブリッドフラスコ"},"Currency":{"category":"カレンシー","category_id":"Currency","name":"カレンシー"},"Amulet":{"category":"アミュレット","category_id":"Amulet","name":"アミュレット","influence_tags":["amulet_crusader","amulet_elder","amulet_basilisk","amulet_eyrie","amulet_shaper","amulet_adjudicator"]},"Ring":{"category":"指輪","category_id":"Ring","name":"指輪","influence_tags":["ring_crusader","ring_elder","ring_basilisk","ring_eyrie","ring_shaper","ring_adjudicator"]},"Claw":{"category":"鉤爪","category_id":"Claw","name":"鉤爪","influence_tags":["claw_crusader","claw_elder","claw_basilisk","claw_eyrie","claw_shaper","claw_adjudicator"]},"Dagger":{"category":"短剣","category_id":"Dagger","name":"短剣","influence_tags":["dagger_crusader","dagger_elder","dagger_basilisk","dagger_eyrie","dagger_shaper","dagger_adjudicator"]},"Wand":{"category":"ワンド","category_id":"Wand","name":"ワンド","influence_tags":["wand_crusader","wand_elder","wand_basilisk","wand_eyrie","wand_shaper","wand_adjudicator"]},"One Hand Sword":{"category":"片手剣","category_id":"One Hand Sword","name":"片手剣","influence_tags":["sword_crusader","sword_elder","sword_basilisk","sword_eyrie","sword_shaper","sword_adjudicator"]},"Thrusting One Hand Sword":{"category":"片手剣","category_id":"One Hand Sword","name":"刺突剣","influence_tags":["sword_crusader","sword_elder","sword_basilisk","sword_eyrie","sword_shaper","sword_adjudicator"]},"One Hand Axe":{"category":"片手斧","category_id":"One Hand Axe","name":"片手斧","influence_tags":["axe_crusader","axe_elder","axe_basilisk","axe_eyrie","axe_shaper","axe_adjudicator"]},"One Hand Mace":{"category":"片手メイス","category_id":"One Hand Mace","name":"片手メイス","influence_tags":["mace_crusader","mace_elder","mace_basilisk","mace_eyrie","mace_shaper","mace_adjudicator"]},"Bow":{"category":"弓","category_id":"Bow","name":"弓","influence_tags":["bow_crusader","bow_elder","bow_basilisk","bow_eyrie","bow_shaper","bow_adjudicator"]},"Staff":{"category":"スタッフ","category_id":"Staff","name":"スタッフ","influence_tags":["staff_crusader","staff_elder","staff_basilisk","staff_eyrie","staff_shaper","staff_adjudicator"]},"Two Hand Sword":{"category":"両手剣","category_id":"Two Hand Sword","name":"両手剣","influence_tags":["2h_sword_crusader","2h_sword_elder","2h_sword_basilisk","2h_sword_eyrie","2h_sword_shaper","2h_sword_adjudicator"]},"Two Hand Axe":{"category":"両手斧","category_id":"Two Hand Axe","name":"両手斧","influence_tags":["2h_axe_crusader","2h_axe_elder","2h_axe_basilisk","2h_axe_eyrie","2h_axe_shaper","2h_axe_adjudicator"]},"Two Hand Mace":{"category":"両手メイス","category_id":"Two Hand Mace","name":"両手メイス","influence_tags":["2h_mace_crusader","2h_mace_elder","2h_mace_basilisk","2h_mace_eyrie","2h_mace_shaper","2h_mace_adjudicator"]},"Active Skill Gem":{"category":"スキルジェム","category_id":"Active Skill Gem","name":"スキルジェム"},"Support Skill Gem":{"category":"サポートジェム","category_id":"Support Skill Gem","name":"サポートジェム"},"Quiver":{"category":"矢筒","category_id":"Quiver","name":"矢筒","influence_tags":["quiver_crusader","quiver_elder","quiver_basilisk","quiver_eyrie","quiver_shaper","quiver_adjudicator"]},"Belt":{"category":"ベルト","category_id":"Belt","name":"ベルト","influence_tags":["belt_crusader","belt_elder","belt_basilisk","belt_eyrie","belt_shaper","belt_adjudicator"]},"Gloves":{"category":"手袋","category_id":"Gloves","name":"手袋","influence_tags":["gloves_crusader","gloves_elder","gloves_basilisk","gloves_eyrie","gloves_shaper","gloves_adjudicator"]},"Boots":{"category":"靴","category_id":"Boots","name":"靴","influence_tags":["boots_crusader","boots_elder","boots_basilisk","boots_eyrie","boots_shaper","boots_adjudicator"]},"Body Armour":{"category":"鎧","category_id":"Body Armour","name":"鎧","influence_tags":["body_armour_crusader","body_armour_elder","body_armour_basilisk","body_armour_eyrie","body_armour_shaper","body_armour_adjudicator"]},"Helmet":{"category":"兜","category_id":"Helmet","name":"兜","influence_tags":["helmet_crusader","helmet_elder","helmet_basilisk","helmet_eyrie","helmet_shaper","helmet_adjudicator"]},"Shield":{"category":"盾","category_id":"Shield","name":"盾","influence_tags":["shield_crusader","shield_elder","shield_basilisk","shield_eyrie","shield_shaper","shield_adjudicator"]},"SmallRelic":{"name":"遺物（小）"},"MediumRelic":{"name":"遺物（中）"},"LargeRelic":{"name":"遺物（大）"},"StackableCurrency":{"category":"カレンシー","category_id":"Currency","name":"スタック可能カレンシー"},"QuestItem":{"category":"クエストアイテム","category_id":"QuestItem","name":"クエストアイテム"},"Sceptre":{"category":"片手メイス","category_id":"One Hand Mace","name":"セプター","influence_tags":["sceptre_crusader","sceptre_elder","sceptre_basilisk","sceptre_eyrie","sceptre_shaper","sceptre_adjudicator"]},"UtilityFlask":{"category":"フラスコ","category_id":"Flask","name":"ユーティリティフラスコ"},"UtilityFlaskCritical":{"category":"フラスコ","category_id":"Flask","name":"クリティカルユーティリティフラスコ"},"Map":{"category":"マップ","category_id":"Map","name":"マップ"},"Unarmed":{"name":""},"FishingRod":{"category":"釣り竿","category_id":"FishingRod","name":"釣り竿"},"MapFragment":{"category":"マップの断片","category_id":"MapFragment","name":"マップの断片"},"HideoutDoodad":{"name":"隠れ家装飾品"},"Microtransaction":{"name":"有料アイテム"},"Jewel":{"category":"ジュエル","category_id":"Jewel","name":"ジュエル"},"DivinationCard":{"category":"占いカード","category_id":"DivinationCard","name":"占いカード"},"LabyrinthItem":{"category":"ラビリンスキー","category_id":"LabyrinthItem","name":"ラビリンスアイテム"},"LabyrinthTrinket":{"category":"ラビリンス宝飾品","category_id":"LabyrinthTrinket","name":"ラビリンス宝飾品"},"LabyrinthMapItem":{"category":"マップの断片","category_id":"MapFragment","name":"ラビリンスマップアイテム"},"MiscMapItem":{"category":"その他マップアイテム","category_id":"MiscMapItem","name":"その他マップアイテム"},"Leaguestone":{"category":"リーグストーン","category_id":"Leaguestone","name":"リーグストーン"},"PantheonSoul":{"category":"捕獲された魂","category_id":"PantheonSoul","name":"パンテオンソウル"},"UniqueFragment":{"category":"ユニークの欠片","category_id":"UniqueFragment","name":"欠片"},"AbyssJewel":{"category":"アビスジュエル","category_id":"AbyssJewel","name":"アビスジュエル"},"IncursionItem":{"category":"インカージョンアイテム","category_id":"IncursionItem","name":"インカージョンアイテム"},"DelveSocketableCurrency":{"category":"レゾネーター","category_id":"DelveSocketableCurrency","name":"デルヴスタック可能カレンシー"},"Incubator":{"category":"インキュベーター","category_id":"Incubator","name":"インキュベーター"},"UniqueShard":{"name":"欠片"},"UniqueShardBase":{"name":"欠片の心臓"},"Rune Dagger":{"category":"短剣","category_id":"Dagger","name":"ルーンの短剣","influence_tags":["rune_dagger_crusader","rune_dagger_elder","rune_dagger_basilisk","rune_dagger_eyrie","rune_dagger_shaper","rune_dagger_adjudicator"]},"Warstaff":{"category":"スタッフ","category_id":"Staff","name":"ウォースタッフ","influence_tags":["warstaff_crusader","warstaff_elder","warstaff_basilisk","warstaff_eyrie","warstaff_shaper","warstaff_adjudicator"]},"DelveStackableSocketableCurrency":{"category":"レゾネーター","category_id":"DelveSocketableCurrency","name":"デルヴスタック可能ソケット可能カレンシー"},"AtlasUpgradeItem":{"category":"ウォッチストーン","category_id":"AtlasUpgradeItem","name":"アトラスアップグレードアイテム"},"MetamorphosisDNA":{"category":"メタモルフサンプル","category_id":"MetamorphosisDNA","name":"メタモルフサンプル"},"HiddenItem":{"name":"隠しアイテム"},"DONOTUSE1":{"name":""},"DONOTUSE2":{"name":""},"DONOTUSE3":{"name":""},"HeistContract":{"category":"依頼書","category_id":"HeistContract","name":"依頼書"},"HeistEquipmentWeapon":{"category":"ハイストギア","category_id":"HeistEquipmentWeapon","name":"ハイストギア"},"HeistEquipmentTool":{"category":"ハイストツール","category_id":"HeistEquipmentTool","name":"ハイストツール"},"HeistEquipmentUtility":{"category":"ハイストクローク","category_id":"HeistEquipmentUtility","name":"ハイストクローク"},"HeistEquipmentReward":{"category":"ハイストブローチ","category_id":"HeistEquipmentReward","name":"ハイストブローチ"},"HeistBlueprint":{"category":"計画書","category_id":"HeistBlueprint","name":"計画書"},"Trinket":{"category":"トリンケット","category_id":"Trinket","name":"トリンケット"},"HeistObjective":{"category":"ハイストターゲット","category_id":"HeistObjective","name":"ハイストターゲット"},"ExpeditionLogbook":{"category":"エクスペディションログブック","category_id":"ExpeditionLogbook","name":"エクスペディションログブック"},"IncubatorStackable":{"category":"インキュベーター","category_id":"Incubator","name":"インキュベーター"},"ArchnemesisMod":{"name":"アーチネメシスモッド"},"DONOTUSE4":{"name":""},"DONOTUSE5":{"name":""},"DONOTUSE6":{"name":""},"DONOTUSE7":{"name":""},"InstanceLocalItem":{"category":"インスタンスローカルアイテム","category_id":"InstanceLocalItem","name":"インスタンスローカルアイテム"},"SentinelDrone":{"category":"センチネルドローン","category_id":"SentinelDrone","name":"センチネル"},"MemoryLine":{"category":"記憶","category_id":"MemoryLine","name":"記憶"},"Relic":{"category":"レリック","category_id":"Relic","name":"レリック"},"SanctumSpecialRelic":{"category":"レリック","category_id":"Relic","name":"聖別されたレリック"},"Breachstone":{"category":"ブリーチストーン","category_id":"Breachstone","name":"ブリーチストーン"},"GiftBox":{"name":""},"VaultKey":{"category":"金庫室の鍵","category_id":"VaultKey","name":"金庫室の鍵"},"ItemisedSanctum":{"category":"その他マップアイテム","category_id":"MiscMapItem","name":"サンクタム調査書"},"Tincture":{"category":"チンキ","category_id":"Tincture","name":"チンキ"},"ItemisedCorpse":{"category":"死体","category_id":"Corpse","name":"死体"},"AnimalCharm":{"category":"チャーム","category_id":"Charm","name":"チャーム"},"NecropolisPack":{"category":"オールフレイムの残り火","category_id":"NecropolisPack","name":"オールフレイムの残り火"}}
